version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: joist
      POSTGRES_PASSWORD: postgres
    volumes:
      - /var/lib/postgresql/data
    ports:
      - 5432:5432
