[tool.black]
line-length = 100
skip-string-normalization = true
target-version = ["py38"]
exclude='.*\.egg-info|\.git|\.mypy_cache|\.pytest_cache|\.tox|\.venv|__pycache__|build|node_modules'

[tool.isort]
profile = "black"
line_length = 100
# Sort by name, don't cluster "from" vs "import"
force_sort_within_sections = true
# Combines "as" imports on the same line
combine_as_imports = true

# test_app is local, but is provided by Django as an absolute import
known_first_party = "test_app"
